name: wakatime-stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs at 00:00 UTC every day
jobs:
  update-readme:
    name: update_repo_readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LANG_COUNT: 5
          COMMIT_MESSAGE: "chore: update stats"
          IGNORED_LANGUAGES: HTML CSS JSON YAML TOML TXT